server:
  port: 9091
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:mysql://localhost:3306/camel
    username: root
    password: Prema@2433
    driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
  database: mysql
  hibernate:
    ddl-auto: update
    show-sql: true


